type City = {
  city: string;
  state: string;
};

export const cities: City[] = [
  { city: 'Aachen', state: 'NW' },
  { city: 'Augsburg', state: 'BY' },
  { city: 'Berlin', state: 'BE' },
  { city: 'Bielefeld', state: 'NW' },
  { city: 'Bochum', state: 'NW' },
  { city: 'Bonn', state: 'NW' },
  { city: 'Braunschweig', state: 'NI' },
  { city: 'Bremen', state: 'HB' },
  { city: 'Bremerhaven', state: 'HB' },
  { city: 'Chemnitz', state: 'SN' },
  { city: 'Cottbus', state: 'BB' },
  { city: 'Dessau-Roßlau', state: 'ST' },
  { city: 'Dortmund', state: 'NW' },
  { city: 'Dresden', state: 'SN' },
  { city: 'Duisburg', state: 'NW' },
  { city: 'Düsseldorf', state: 'NW' },
  { city: 'Elze', state: 'NI' },
  { city: 'Erfurt', state: 'TH' },
  { city: 'Essen', state: 'NW' },
  { city: 'Flensburg', state: 'SH' },
  { city: 'Frankfurt am Main', state: 'HE' },
  { city: 'Freiberg', state: 'SN' },
  { city: 'Freiburg im Breisgau', state: 'BW' },
  { city: 'Friedrichshafen', state: 'BW' },
  { city: 'Gera', state: 'TH' },
  { city: 'Gießen', state: 'HE' },
  { city: 'Göttingen', state: 'NI' },
  { city: 'Gütersloh', state: 'NW' },
  { city: 'Halle (Saale)', state: 'ST' },
  { city: 'Hamburg', state: 'HH' },
  { city: 'Hamm', state: 'NW' },
  { city: 'Hannover', state: 'NI' },
  { city: 'Heidelberg', state: 'BW' },
  { city: 'Heilbronn', state: 'BW' },
  { city: 'Ingolstadt', state: 'BY' },
  { city: 'Iserlohn', state: 'NW' },
  { city: 'Jena', state: 'TH' },
  { city: 'Karlsruhe', state: 'BW' },
  { city: 'Kassel', state: 'HE' },
  { city: 'Kiel', state: 'SH' },
  { city: 'Koblenz', state: 'RP' },
  { city: 'Köln', state: 'NW' },
  { city: 'Konstanz', state: 'BW' },
  { city: 'Krefeld', state: 'NW' },
  { city: 'Leipzig', state: 'SN' },
  { city: 'Lübeck', state: 'SH' },
  { city: 'Ludwigshafen', state: 'RP' },
  { city: 'Magdeburg', state: 'ST' },
  { city: 'Mainz', state: 'RP' },
  { city: 'Mannheim', state: 'BW' },
  { city: 'Marburg', state: 'HE' },
  { city: 'Mönchengladbach', state: 'NW' },
  { city: 'Mülheim an der Ruhr', state: 'NW' },
  { city: 'München', state: 'BY' },
  { city: 'Münster', state: 'NW' },
  { city: 'Neuss', state: 'NW' },
  { city: 'Neustadt an der Weinstraße', state: 'RP' },
  { city: 'Nürnberg', state: 'BY' },
  { city: 'Oberhausen', state: 'NW' },
  { city: 'Oldenburg', state: 'NI' },
  { city: 'Osnabrück', state: 'NI' },
  { city: 'Paderborn', state: 'NW' },
  { city: 'Pforzheim', state: 'BW' },
  { city: 'Potsdam', state: 'BB' },
  { city: 'Regensburg', state: 'BY' },
  { city: 'Reutlingen', state: 'BW' },
  { city: 'Remscheid', state: 'NW' },
  { city: 'Rostock', state: 'MV' },
  { city: 'Saarbrücken', state: 'SL' },
  { city: 'Schwerin', state: 'MV' },
  { city: 'Seelze', state: 'NI' },
  { city: 'Sindelfingen', state: 'BW' },
  { city: 'Solingen', state: 'NW' },
  { city: 'Stuttgart', state: 'BW' },
  { city: 'Trier', state: 'RP' },
  { city: 'Tübingen', state: 'BW' },
  { city: 'Uelzen', state: 'NI' },
  { city: 'Ulm', state: 'BW' },
  { city: 'Villingen-Schwenningen', state: 'BW' },
  { city: 'Wiesbaden', state: 'HE' },
  { city: 'Witten', state: 'NW' },
  { city: 'Wolfsburg', state: 'NI' },
  { city: 'Worms', state: 'RP' },
  { city: 'Wuppertal', state: 'NW' },
  { city: 'Würzburg', state: 'BY' },
  { city: 'Zwickau', state: 'SN' },
];
